name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 4: Fix vulnerabilities
      - name: Fix vulnerabilities
        run: |
          npm audit fix || echo "Unable to fix all vulnerabilities."
          npm audit fix --force || echo "Force fixes applied where possible."

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: Ae2HvRvsv1TAcIdtbVQlgGS3
          vercel-project-id: habisyncs-projects
          vercel-org-id: YCGA2BOsynXPOqogWLS8nZvJ
